### ISSUE TITLE
Please migrate away from nose for testing

### ISSUE THREAD

**Issue by llimeht** [jwilk/i18nspector#7]
Apparently `nose` will soon cease to work for `setuptools`; while that doesn't directly affect i18nspector, the end is nigh for it in Debian as well, and it's obviously my preference to keep running build-time and autopkgtest tests on i18nspector.

https://lists.debian.org/debian-python/2021/10/msg00058.html

Is there a plan to migrate to a different test harness? The migration looks moderately painful but certainly doable to either `unittest` or `py.test` (the latter probably being easier).

**Comment by jwilk** [comment]
Fixed in [0.27.1](https://github.com/jwilk/i18nspector/releases/tag/0.27.1).
